export const BOOK_REPOSITORY = Symbol('BOOK_REPOSITORY');
export const AUTHOR_REPOSITORY = Symbol('AUTHOR_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const GENRE_REPOSITORY = Symbol('GENRE_REPOSITORY');
export const SERIES_REPOSITORY = Symbol('SERIES_REPOSITORY');
export const REVIEW_REPOSITORY = Symbol('REVIEW_REPOSITORY');
export const USER_BOOK_LIST_REPOSITORY = Symbol('USER_BOOK_LIST_REPOSITORY');
